### ISSUE TITLE
Unable to use !Sub for !Ref for Name of StringFunctions macro

### ISSUE THREAD

**Issue by Vincent-Le** [aws-cloudformation/aws-cloudformation-templates#239]
I need to create a unique name for the string macro by concatenating the stack name. For example, ${AWS::StackName}-MyString

```
  TransformFunctionPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt TransformFunction.Arn
      Principal: 'cloudformation.amazonaws.com'
  Transform:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: !Sub ${AWS::StackName}-MyStringFunctions
      Description: Provides various string processing functions
      FunctionName: !GetAtt TransformFunction.Arn
```

However, when I tried to use !Sub (or !Ref) to call the transform StringFunctions, it doesn't like it:

      RepositoryName:
        'Fn::Transform':
         - Name: !Sub ${AWS::StackName}-MyStringFunctions
           Parameters:
             InputString: 'MyValue'
             Operation: Lower

The `Name` has to be a static name (e.g., MyStringFunctions) and I cannot use !Sub or !Ref
