### ISSUE TITLE
MacrosExamples - ExecutionRoleBuilder update and typo

### ISSUE THREAD

**Issue by Onolisk** [aws-cloudformation/aws-cloudformation-templates#391]
Hi, an update is required for the awslabs sample here: 

https://github.com/awslabs/aws-cloudformation-templates/tree/master/aws/services/CloudFormation/MacrosExamples/ExecutionRoleBuilder

A simple typo in step 4 prevents inexperienced users from progressing. Python runtime to be updated 3.9 as the version specified is deprecated on AWS.

README.md

step 4:

OLD:
```
aws cloudformation deploy \
    --stack-name ExecutionRoleBuilderCFnMacro.packaged.template \
    --template-file ExecutionRoleBuilderCFnMacro \
    --capabilities CAPABILITY_IAM
```

NEW:
```
aws cloudformation deploy \
    --stack-name ExecutionRoleBuilderCFnMacro \
    --template-file ExecutionRoleBuilderCFnMacro.packaged.template  \
    --capabilities CAPABILITY_IAM
```

macro.template:

```
Transform: AWS::Serverless-2016-10-31
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
```
